-- MySQL Script generated by MySQL Workbench
-- Tue Aug 20 08:45:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema relojvital
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `relojvital` ;

-- -----------------------------------------------------
-- Schema relojvital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relojvital` DEFAULT CHARACTER SET utf8mb3 ;
USE `relojvital` ;

-- -----------------------------------------------------
-- Table `relojvital`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relojvital`.`sensor` ;

CREATE TABLE IF NOT EXISTS `relojvital`.`sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `relojvital`.`datosensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relojvital`.`datosensor` ;

CREATE TABLE IF NOT EXISTS `relojvital`.`datosensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `fecha` DATE NOT NULL,
  `fkSensor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_datoSensor_sensor_idx` (`fkSensor` ASC) VISIBLE,
  CONSTRAINT `fk_datoSensor_sensor`
    FOREIGN KEY (`fkSensor`)
    REFERENCES `relojvital`.`sensor` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `relojvital`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relojvital`.`usuario` ;

CREATE TABLE IF NOT EXISTS `relojvital`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(10) NOT NULL,
  `estatura` FLOAT NOT NULL,
  `peso` FLOAT NOT NULL,
  `meta` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
